apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-project
spec:
  selector:
    matchLabels:
      app: my-project
  replicas: 1
  template:
    metadata:
      labels:
        app: my-project
    spec:
      containers:
      - name: my-project
        image: sahil1012/myubuntu
        ports:
        - containerPort: 80
